# install: ./install-dependencies.sh
language: python
# - virtualenv --python=python venv
#   - source venv/bin/activate
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
script:
  - pip install .
