language: generic
os: osx
compiler:
    - clang
before_install:
    - brew update
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda config --set anaconda_upload no
install:
    - conda install -q -y conda-build setuptools numpy cython matplotlib scikit-learn h5py scipy pandas anaconda-client
    - conda build conda-recipe
    - conda install --use-local limix
script:
    - python setup.py test
deploy:
  - provider: script
    script: deploy/travis_conda.sh
    on:
      tags: true
    skip_cleanup: true
