language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get install -y libblas-dev libatlas-dev liblapack-dev > /dev/null
    - pip install numpy --quiet
    - pip install scipy --quiet
    - pip install matplotlib
install:
    - python setup.py install --quiet

script:
    - python tests/run_all.py

