sudo: required
services: docker
language: python

python:
    - 2.7

env:
    - IMG_BASE=science-conda2
    - IMG_BASE=science-canopy2
    - IMG_BASE=science-bare

addons:
    apt:
        packages:
            - build-essential
            - libc6
            - g++
            - gfortran

before_install:
    - docker pull dhorta/$IMG_BASE

script:
    - ./docker-test.sh $IMG_BASE
