
#get all the build variables we need
Import('env','build_options')
localenv = env.Clone()


srclst = Glob('*/*.cpp')

#srclst
#localenv.Depends(srclst, [libnlopt])

lib=localenv.StaticLibrary('limix',srclst)
Return('lib')
