
#get all the build variables we need
Import('env','libnlopt','build_options')
localenv = env.Clone()


srclst = Glob('*/*.cpp')

#srclst
localenv.Depends(srclst, [libnlopt])

#srclst.extend(Glob('io/vcf/*.c*'))
#srclst.extend(Glob('io/vcf/multichoose/*.c*'))
#srclst.extend(Glob('io/vcf/smithwaterman/*.c*'))
#if build_options['with_zlib']:
#   srclst.extend(Glob('io/vcf/tabixpp/*.c*'))

lib=localenv.StaticLibrary('limix',srclst)
Return('lib')
