
#get all the build variables we need
Import('env','libnlopt','build_options')
localenv = env.Clone()


srclst = Glob('*/*.cpp')

#srclst
localenv.Depends(srclst, [libnlopt])

if build_options['with_vcf']:
   srclst.extend(Glob('io/vcf/*.c*'))
   srclst.extend(Glob('io/vcf/*/*.c*'))

lib=localenv.StaticLibrary('limix',srclst)
Return('lib')
