#!/bin/bash

echo "Installing Limix."

sudo apt-get update
sudo apt-get -y -q install build-essential libc6 gfortran g++ \
     python python-setuptools cython python-numpy python-scipy \
     python-matplotlib pkg-config libfreetype6-dev libpng12-dev \
     python-h5py liblapack-dev python-pip python-pandas swig \
     python-sklearn
pip install limix
