#!/bin/bash

anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
conda config --set anaconda_upload yes
conda config --add channels https://conda.anaconda.org/horta
conda build conda-recipe
