#!/bin/bash

echo "Installing Limix."

prefix=""
if type "sudo" > /dev/null 2>&1; then
    prefix="sudo "
fi

eval "${prefix}dnf update -y"
eval "${prefix}dnf install gcc-gfortran python Cython numpy python-matplotlib \
            python-pkgconfig h5py lapack-devel python-pip python-pandas \
            swig python-scikit-learn gcc-c++ redhat-rpm-config scipy -y"
pip install limix
