#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo -n "Wrong number of arguments. You must supply Limix version "
    echo "as the first argument."
    exit 1
fi
LIMIX_VERSION=$1

export REMOTE_REPOSITORY="https://github.com/PMBio/limix.git"
export REMOTE_BRANCH="production"

set -e

if [[ ! -z $CI_COMMIT_ID ]]; then
    echo "Trying to deploy Limix ${LIMIX_VERSION} to GitHub."
    ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
    git fetch --unshallow || true
    git tag v${LIMIX_VERSION}
    git push ${REMOTE_REPOSITORY} ${CI_COMMIT_ID}:${REMOTE_BRANCH} --tags
else
    echo "We won't try to deploy it because CI_COMMIT_ID is missing."
    exit 1
fi
