#!/bin/bash

echo "Installing Limix."

prefix=""
if type "sudo" > /dev/null 2>&1; then
    prefix="sudo "
fi

eval "${prefix}zypper -n update"
eval "${prefix}zypper -n install libgfortran3 python python-Cython python-numpy \
                              python-numpy-devel python-scipy \
                              python-matplotlib python-pkgconfig \
                              python-h5py python-pip swig gcc-c++"
pip install limix
