package:
    name: limix
    version: "0.7.71"

source:
    path: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - matplotlib
    - scikit-learn
    - h5py
    - scipy
    - pandas
    - gcc 4.8.* # [osx]
    - swig
  run:
    - python
    - numpy
    - cython
    - matplotlib
    - scikit-learn
    - h5py
    - scipy
    - pandas
    - libgcc 4.8.* # [osx]
    - swig
about:
  home: https://github.com/PMBio/limix
  license: Apache License
  license_file: license.txt
