package:
    name: limix
    version: "0.7.50"

source:
    fn: v0.7.50.tar.gz
    url: https://github.com/PMBio/limix/archive/v0.7.50.tar.gz

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - matplotlib
    - scikit-learn
    - h5py
    - scipy
  run:
    - python
    - numpy
    - cython
    - matplotlib
    - scikit-learn
    - h5py
    - scipy

build:
  script: python setup.py install

about:
  home: https://github.com/PMBio/limix
  license: Apache License
  license_file: license.txt
