package:
    name: limix
    version: "0.7.53"

# source:
#     fn: v0.7.53.tar.gz
#     url: https://github.com/PMBio/limix/archive/v0.7.53.tar.gz

source:
    path: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - matplotlib
    - scikit-learn
    - h5py
    - scipy
    - pandas
  run:
    - python
    - numpy
    - cython
    - matplotlib
    - scikit-learn
    - h5py
    - scipy
    - pandas

about:
  home: https://github.com/PMBio/limix
  license: Apache License
  license_file: license.txt
