resources:

- name: limix
  type: git
  source:
    uri: https://github.com/PMBio/limix
    branch: master

# - name: gh-release
#   type: github-release
#   source:
#     user: PMBio
#     repository: limix
#     access_token: abcdef1234567890

jobs:

- name: test-from-source
  plan:
  - get: limix
    trigger: true
  - aggregate:
    - task: test-conda2
      file: limix/ci/test-conda2.yml
    - task: test-conda3
      file: limix/ci/test-conda3.yml

- name: test-sdist
  plan:
  - get: limix
    passed: [test-from-source]
    trigger: true
  - task: build-sdist
    file: limix/ci/build-sdist.yml
  - task: test-sdist
    file: limix/ci/test-sdist.yml

- name: deploy-sdist
  plan:
  - get: limix
    passed: [test-sdist]
    trigger: true
  - task: build-sdist
    file: limix/ci/build-sdist.yml
  - task: deploy-sdist
    file: limix/ci/deploy-sdist.yml
    attempts: 5
