import glob

#get all the build variables we need
Import('env', 'project', 'mymode', 'debugcflags', 'releasecflags')
localenv = env.Clone()

srclst = Glob('limix/*/*.cpp')


lib=localenv.StaticLibrary('limix',srclst)
Return('lib')